# Generated by Django 3.2.5 on 2021-07-10 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gp',
            fields=[
                ('pais', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('circuito', models.CharField(max_length=50)),
                ('data_corrida', models.DateField(verbose_name='Data da corrida')),
                ('hora_corrida', models.TimeField(verbose_name='hora da corrida')),
            ],
            options={
                'db_table': 'gps',
            },
        ),
        migrations.CreateModel(
            name='Piloto',
            fields=[
                ('nome', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('equipe', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'pilotos',
            },
        ),
        migrations.CreateModel(
            name='Aposta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('decimo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piloto_10', to='bolaodoego.piloto')),
                ('gp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bolaodoego.gp')),
                ('nono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piloto_9', to='bolaodoego.piloto')),
                ('oitavo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piloto_8', to='bolaodoego.piloto')),
                ('primeiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piloto_1', to='bolaodoego.piloto')),
                ('quarto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piloto_4', to='bolaodoego.piloto')),
                ('quinto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piloto_5', to='bolaodoego.piloto')),
                ('segundo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piloto_2', to='bolaodoego.piloto')),
                ('setimo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piloto_7', to='bolaodoego.piloto')),
                ('sexto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piloto_6', to='bolaodoego.piloto')),
                ('terceiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piloto_3', to='bolaodoego.piloto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'apostas',
            },
        ),
    ]
