# Generated by Django 3.2.5 on 2021-07-12 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bolaodoego', '0002_resultado'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado',
            name='data_corrida',
            field=models.ForeignKey(default=2021, on_delete=django.db.models.deletion.CASCADE, related_name='data', to='bolaodoego.gp'),
            preserve_default=False,
        ),
    ]
