# Generated by Django 3.2.5 on 2021-07-12 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bolaodoego', '0003_resultado_data_corrida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultado',
            name='data_corrida',
        ),
    ]
